version: "3.7"

services:

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 6445:5432

  app:
    build: .
    volumes:
      - ./src:/src:rw
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - default
      - common-net
    ports:
      - 9070:8000

networks:
  default:
    driver: bridge
  common-net:
    external: true