"""init

Revision ID: 4085959806fa
Revises: 
Create Date: 2023-01-21 00:35:43.593731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4085959806fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # 前処理
    pre_upgrade()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True, comment='Идентификатор сокращенной ссылки'),
    sa.Column('original_link', sa.String(), nullable=False, comment='Оригинальная ссылка'),
    sa.Column('end_date', sa.DateTime(), nullable=False, comment='Дата и время окончания срока действия сокращенной ссылки'),
    sa.Column('date_category', sa.String(length=64), nullable=False, comment='Категория для формирования  срока действия сокращенной ссылки'),
    sa.Column('date_quantity', sa.Integer(), nullable=False, comment='Количество для формирования  срока действия сокращенной ссылки'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###
    post_upgrade()


def downgrade():
    # 前処理
    pre_downgrade()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    # ### end Alembic commands ###


    post_downgrade()


def pre_upgrade():
    pass


def post_upgrade():

    pass


def pre_downgrade():
    pass


def post_downgrade():
    pass